export const styles = {
  container: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    padding: '20px',
  },
  card: {
    background: '#ffffff',
    padding: '48px 40px',
    borderRadius: '16px',
    width: '100%',
    maxWidth: '420px',
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.3)',
  },
  header: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    marginBottom: '32px',
  },
  logo: {
    width: '64px',
    height: '64px',
    borderRadius: '16px',
    background: 'linear-gradient(135deg, #d4af37 0%, #f5d76e 100%)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '32px',
    marginBottom: '16px',
  },
  title: {
    fontSize: '24px',
    fontWeight: '700',
    color: '#1a1a2e',
    margin: '0 0 4px 0',
  },
  subtitle: {
    color: '#666',
    fontSize: '14px',
    margin: 0,
  },
  form: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '6px',
  },
  label: {
    color: '#333',
    fontSize: '13px',
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
  },
  phoneInputContainer: {
    display: 'flex',
    alignItems: 'stretch',
    borderRadius: '10px',
    border: '2px solid #e8e8e8',
    background: '#fafafa',
    overflow: 'hidden',
    transition: 'all 0.3s ease',
  },
  phoneInputContainerFocus: {
    borderColor: '#d4af37',
    background: '#fff',
    boxShadow: '0 0 0 3px rgba(212, 175, 55, 0.1)',
  },
  phoneInputContainerError: {
    borderColor: '#e74c3c',
    background: '#fff',
  },
  countryCode: {
    display: 'flex',
    alignItems: 'center',
    padding: '0 14px',
    background: '#f0f0f0',
    color: '#333',
    fontSize: '15px',
    fontWeight: '600',
    borderRight: '2px solid #e8e8e8',
    whiteSpace: 'nowrap',
  },
  phoneInput: {
    flex: 1,
    padding: '14px 16px',
    border: 'none',
    background: 'transparent',
    color: '#333',
    fontSize: '15px',
    outline: 'none',
    letterSpacing: '2px',
  },
  input: {
    padding: '14px 16px',
    borderRadius: '10px',
    border: '2px solid #e8e8e8',
    background: '#fafafa',
    color: '#333',
    fontSize: '15px',
    transition: 'all 0.3s ease',
    outline: 'none',
    width: '100%',
  },
  inputFocus: {
    borderColor: '#d4af37',
    background: '#fff',
    boxShadow: '0 0 0 3px rgba(212, 175, 55, 0.1)',
  },
  inputError: {
    borderColor: '#e74c3c',
    background: '#fff',
  },
  errorText: {
    color: '#e74c3c',
    fontSize: '12px',
    marginTop: '4px',
  },
  button: {
    padding: '14px',
    borderRadius: '10px',
    border: 'none',
    background: 'linear-gradient(135deg, #d4af37 0%, #c19b2e 100%)',
    color: '#fff',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    marginTop: '8px',
    width: '100%',
  },
  buttonDisabled: {
    opacity: 0.6,
    cursor: 'not-allowed',
  },
  buttonHover: {
    transform: 'translateY(-1px)',
    boxShadow: '0 4px 12px rgba(212, 175, 55, 0.4)',
  },
  footer: {
    marginTop: '24px',
    textAlign: 'center',
  },
  footerText: {
    fontSize: '13px',
    color: '#999',
    margin: 0,
  },
};