export const styles = {
  layout: {
    display: 'flex',
    minHeight: '100vh',
    background: '#ffffff',
  },
  
  // Mobile Header
  mobileHeader: {
    display: 'none',
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    height: '56px',
    background: '#ffffff',
    color: '#1a1a2e',
    padding: '0 16px',
    zIndex: 1000,
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottom: '2px solid #000000',
  },
  menuToggle: {
    background: 'none',
    border: '1px solid #000000',
    color: '#000000',
    fontSize: '24px',
    cursor: 'pointer',
    padding: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: '8px',
    transition: 'all 0.2s',
  },
  mobileLogo: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  logoIcon: {
    fontSize: '22px',
  },
  logoText: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#000000',
  },
  mobileAvatar: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    background: '#d4af37',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: '700',
    fontSize: '14px',
    border: '2px solid #000000',
  },

  // Sidebar
  sidebar: {
    width: '260px',
    minWidth: '260px',
    background: '#ffffff',
    color: '#1a1a2e',
    display: 'flex',
    flexDirection: 'column',
    height: '100vh',
    position: 'sticky',
    top: 0,
    transition: 'transform 0.3s ease',
    zIndex: 999,
    borderRight: '2px solid #000000',
  },
  sidebarContent: {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    overflowY: 'auto',
    overflowX: 'hidden',
  },
  sidebarLogo: {
    padding: '20px 20px 16px',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    borderBottom: '2px solid #000000',
  },
  
  // Navigation
  nav: {
    flex: 1,
    padding: '8px 0',
    overflowY: 'auto',
  },
  navItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 20px',
    width: '100%',
    background: 'none',
    border: 'none',
    color: '#4a5568',
    cursor: 'pointer',
    textAlign: 'left',
    fontSize: '14px',
    transition: 'all 0.2s ease',
    borderLeft: '3px solid transparent',
    position: 'relative',
  },
  navItemActive: {
    background: '#d4af37',
    color: '#000000',
    borderLeft: '3px solid #000000',
    fontWeight: '600',
  },
  navItemHover: {
    background: '#faf5e8',
    color: '#1a1a2e',
  },
  navIcon: {
    fontSize: '18px',
    width: '24px',
    textAlign: 'center',
    flexShrink: 0,
  },
  navLabel: {
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    minWidth: 0,
  },
  navTitle: {
    fontSize: '14px',
    fontWeight: '500',
    lineHeight: '1.3',
  },
  navDescription: {
    fontSize: '11px',
    color: 'inherit',
    opacity: 0.7,
    lineHeight: '1.2',
  },
  navIndicator: {
    position: 'absolute',
    right: '12px',
    width: '6px',
    height: '6px',
    borderRadius: '50%',
    background: '#000000',
  },

  // Sidebar Footer
  sidebarFooter: {
    padding: '16px 20px',
    borderTop: '2px solid #000000',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    background: '#fafafa',
  },
  userProfile: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  userAvatar: {
    width: '40px',
    height: '40px',
    borderRadius: '10px',
    background: '#d4af37',
    color: '#ffffff',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: '700',
    fontSize: '16px',
    flexShrink: 0,
    border: '2px solid #000000',
  },
  userInfo: {
    display: 'flex',
    flexDirection: 'column',
    minWidth: 0,
  },
  userName: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#000000',
    margin: 0,
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  userRole: {
    fontSize: '12px',
    color: '#d4af37',
    margin: 0,
    textTransform: 'capitalize',
    fontWeight: '600',
  },
  logoutBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '10px 16px',
    background: '#ffffff',
    border: '2px solid #000000',
    borderRadius: '8px',
    color: '#000000',
    cursor: 'pointer',
    fontSize: '14px',
    fontWeight: '600',
    transition: 'all 0.2s',
    width: '100%',
  },
  logoutBtnHover: {
    background: '#000000',
    color: '#d4af37',
    border: '2px solid #d4af37',
  },

  // Overlay
  overlay: {
    display: 'none',
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: 'rgba(0, 0, 0, 0.6)',
    zIndex: 998,
  },

  // Main Content
  mainContent: {
    flex: 1,
    minWidth: 0,
    overflow: 'auto',
    background: '#ffffff',
  },
  contentWrapper: {
    padding: '28px 32px',
    maxWidth: '1400px',
    margin: '0 auto',
    width: '100%',
  },

  // Media Queries
  '@media (max-width: 768px)': {
    mobileHeader: {
      display: 'flex',
    },
    sidebar: {
      position: 'fixed',
      left: 0,
      top: 0,
      bottom: 0,
      transform: 'translateX(-100%)',
      zIndex: 999,
    },
    sidebarOpen: {
      transform: 'translateX(0)',
    },
    overlayVisible: {
      display: 'block',
    },
    mainContent: {
      paddingTop: '56px',
    },
    contentWrapper: {
      padding: '16px',
    },
  },
};